// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CreateSaleRequestLine {
    productId: number;
    quantity: number;
    discountCents: number;
}

export interface CreateSaleRequest {
    saleNumber: string;
    customerName: string;
    paymentMethod: string;
    discountCents: number;
    lines: CreateSaleRequestLine[];
}

export interface SaleLine {
    productId: number;
    productName: string;
    sku: string;
    quantity: number;
    unitPriceCents: number;
    discountCents: number;
    taxCents: number;
    lineTotalCents: number;
}

export interface Sale {
    id: number;
    saleNumber: string;
    customerName: string;
    subtotalCents: number;
    discountCents: number;
    taxCents: number;
    totalCents: number;
    paymentMethod: string;
    status: string;
    lines: SaleLine[];
}

export function CreateSale(arg1: CreateSaleRequest): Promise<Sale>;

export function ListSales(arg1: string, arg2: string): Promise<Sale[]>;

export function RefundSale(arg1: number): Promise<void>;
