// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSale(arg1) {
  return window['go']['sale']['API']['CreateSale'](arg1);
}

export function ListSales(arg1, arg2) {
  return window['go']['sale']['API']['ListSales'](arg1, arg2);
}

export function RefundSale(arg1) {
  return window['go']['sale']['API']['RefundSale'](arg1);
}
