// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sale} from '../models';

export function CreateSale(arg1:sale.CreateSaleRequest):Promise<sale.Sale>;

export function ListSales(arg1:string,arg2:string):Promise<Array<sale.Sale>>;

export function RefundSale(arg1:number):Promise<void>;
