// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sale} from '../models';

export function CreateSale(arg1:context.Context,arg2:sale.CreateSaleRequest):Promise<sale.Sale>;

export function ListSales(arg1:context.Context,arg2:string,arg3:string):Promise<Array<sale.Sale>>;

export function RefundSale(arg1:context.Context,arg2:number):Promise<void>;
