// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {product} from '../models';

export function CreateProduct(arg1:product.ProductInput):Promise<product.ProductView>;

export function ListProducts():Promise<Array<product.ProductView>>;
