// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {product} from '../models';

export function CreateProduct(arg1:context.Context,arg2:product.ProductInput):Promise<product.ProductView>;

export function ListProducts(arg1:context.Context):Promise<Array<product.ProductView>>;
