// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProductInput {
    name: string;
    sku: string;
    unitPriceCents: number;
    taxRate: number;
    stockQuantity: number;
    reorderLevel: number;
    notes: string;
}

export interface ProductView {
    id: number;
    name: string;
    sku: string;
    unitPriceCents: number;
    taxRate: number;
    stockQuantity: number;
    reorderLevel: number;
    notes: string;
}

export function CreateProduct(arg1: ProductInput): Promise<ProductView>;

export function ListProducts(): Promise<ProductView[]>;
