// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
    return window['go']['product']['API']['CreateProduct'](arg1);
}

export function ListProducts() {
    return window['go']['product']['API']['ListProducts']();
}
