// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DailySummary(arg1) {
    return window['go']['report']['API']['DailySummary'](arg1);
}

export function TopProducts(arg1, arg2, arg3) {
    return window['go']['report']['API']['TopProducts'](arg1, arg2, arg3);
}
