// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {report} from '../models';

export function DailySummary(arg1:context.Context,arg2:string):Promise<report.DailySummary>;

export function TopProducts(arg1:context.Context,arg2:string,arg3:string,arg4:number):Promise<Array<report.TopProduct>>;
