// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DailySummaryResult {
    date: string;
    totalSales: number;
    invoiceCount: number;
    averageTicket: number;
    taxCollected: number;
}

export interface TopProductResult {
    productId: number;
    productName: string;
    quantitySold: number;
    revenueCents: number;
}

export function DailySummary(arg1: string): Promise<DailySummaryResult>;

export function TopProducts(arg1: string, arg2: string, arg3: number): Promise<TopProductResult[]>;
