// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create() {
    return window['go']['backup']['API']['Create']();
}

export function List(arg1) {
    return window['go']['backup']['API']['List'](arg1);
}
