// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BackupRecord {
    id: number;
    filename: string;
    sizeBytes: number;
    createdAt: string;
}

export function Create(): Promise<BackupRecord>;

export function List(arg1: number): Promise<BackupRecord[]>;
