// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['backup']['API']['Create'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['backup']['API']['List'](arg1, arg2);
}
