// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {backup} from '../models';

export function Create(arg1:context.Context):Promise<backup.Record>;

export function List(arg1:context.Context,arg2:number):Promise<Array<backup.Record>>;
