// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backups() {
  return window['go']['app']['App']['Backups']();
}

export function HealthPing(arg1) {
  return window['go']['app']['App']['HealthPing'](arg1);
}

export function Products() {
  return window['go']['app']['App']['Products']();
}

export function Reports() {
  return window['go']['app']['App']['Reports']();
}

export function Sales() {
  return window['go']['app']['App']['Sales']();
}
