// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {product} from '../models';
import {report} from '../models';
import {sale} from '../models';

export function Backups():Promise<backup.API>;

export function HealthPing(arg1:string):Promise<string>;

export function Products():Promise<product.API>;

export function Reports():Promise<report.API>;

export function Sales():Promise<sale.API>;
